global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
