server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask
          __path__: /var/log/flask/*.log
  - job_name: docker-stdout
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          container_name: app
          __path__: /var/lib/docker/containers/*/*-json.log
